/*
 * myrt_config.h
 *
 * Created: 2018-02-24 12:36:57
 *  Author: Nikodem Kastelik
 */ 


#ifndef MYRT_CONFIG_H_
#define MYRT_CONFIG_H_

#define TASKS_COUNT 3
#define TASKS_COUNT_WITH_IDLE (TASKS_COUNT+1)

#define SYSTICK_TIMER_ISR TIMER0_OVF_vect

#define PCL_STACK_INDEX 0
#define PCH_STACK_INDEX -1
#define TASK_CPU_REGISTERS_SIZE 0x20
#define TASK_SCHEDULER_RETURN_ADDR_SIZE 0x02
#define TASK_PC_SIZE 0x02
#define TASK_SREG_SIZE 0x01
#define SREG_STACK_INDEX -0x22
#define TASK_MINIMUM_STACK_SIZE (TASK_CPU_REGISTERS_SIZE + TASK_SCHEDULER_RETURN_ADDR_SIZE + TASK_PC_SIZE)
#define TASK_ALL_REGISTERS_SIZE (TASK_CPU_REGISTERS_SIZE + TASK_PC_SIZE)

#define FIRST_TASK 0
#define IDLE_TASK TASKS_COUNT

#define IDLE_TASK_MINIMUM_STACK_SIZE (TASK_CPU_REGISTERS_SIZE + 0x0b)
#define IDLE_TASK_USER_STACK_SIZE 0
#define IDLE_TASK_TOTAL_STACK_SIZE (IDLE_TASK_MINIMUM_STACK_SIZE + IDLE_TASK_USER_STACK_SIZE)


#endif /* MYRT_CONFIG_H_ */